import type { Customer, Order } from "@/types";

import { PRODUCT_IMAGES } from "./media";

export const CUSTOMERS: Customer[] = [
  {
    id: "c-001",
    name: "Amelia Rivers",
    email: "amelia@example.com",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/png?seed=Amelia",
    totalOrders: 12,
    totalSpent: 4280,
    status: "active",
    joinedAt: "2024-04-12T00:00:00.000Z",
  },
  {
    id: "c-002",
    name: "James Kessler",
    email: "james@example.com",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/png?seed=James",
    totalOrders: 6,
    totalSpent: 1890,
    status: "active",
    joinedAt: "2025-01-22T00:00:00.000Z",
  },
  {
    id: "c-003",
    name: "Sofia Chen",
    email: "sofia@example.com",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/png?seed=Sofia",
    totalOrders: 18,
    totalSpent: 7240,
    status: "active",
    joinedAt: "2023-11-05T00:00:00.000Z",
  },
  {
    id: "c-004",
    name: "Marcus Wright",
    email: "marcus@example.com",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/png?seed=Marcus",
    totalOrders: 3,
    totalSpent: 612,
    status: "inactive",
    joinedAt: "2025-09-18T00:00:00.000Z",
  },
  {
    id: "c-005",
    name: "Priya Patel",
    email: "priya@example.com",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/png?seed=Priya",
    totalOrders: 9,
    totalSpent: 3120,
    status: "active",
    joinedAt: "2024-08-30T00:00:00.000Z",
  },
];

export const ORDERS: Order[] = [
  {
    id: "o-1001",
    number: "LX-10241",
    customer: { id: "c-001", name: "Amelia Rivers", email: "amelia@example.com" },
    items: [
      {
        id: "ci-1",
        productId: "p-001",
        productSlug: "milano-cashmere-coat",
        name: "Milano Cashmere Coat",
        imageUrl: PRODUCT_IMAGES["p-001"][0],
        price: 489,
        quantity: 1,
        variantId: "p-001-color-black-size-m",
        colorId: "color-black",
        colorName: "Onyx Black",
        sizeId: "size-m",
        sizeLabel: "M",
        stock: 12,
      },
    ],
    subtotal: 489,
    shipping: 0,
    tax: 39.12,
    discount: 0,
    total: 528.12,
    status: "delivered",
    paymentMethod: "card",
    shippingMethod: "express",
    shippingAddress: {
      fullName: "Amelia Rivers",
      email: "amelia@example.com",
      phone: "+1 555 012 0001",
      line1: "421 W Broadway",
      city: "New York",
      state: "NY",
      postalCode: "10012",
      country: "United States",
    },
    trackingNumber: "1Z999AA10123456784",
    createdAt: "2026-04-22T10:00:00.000Z",
    updatedAt: "2026-04-26T18:00:00.000Z",
  },
  {
    id: "o-1002",
    number: "LX-10242",
    customer: { id: "c-002", name: "James Kessler", email: "james@example.com" },
    items: [
      {
        id: "ci-2",
        productId: "p-002",
        productSlug: "luca-leather-derby",
        name: "Luca Leather Derby",
        imageUrl: PRODUCT_IMAGES["p-002"][0],
        price: 349,
        quantity: 1,
        variantId: "p-002-color-black-size-9",
        colorId: "color-black",
        colorName: "Onyx Black",
        sizeId: "size-9",
        sizeLabel: "US 9",
        stock: 8,
      },
    ],
    subtotal: 349,
    shipping: 6.99,
    tax: 27.92,
    discount: 0,
    total: 383.91,
    status: "shipped",
    paymentMethod: "card",
    shippingMethod: "standard",
    shippingAddress: {
      fullName: "James Kessler",
      email: "james@example.com",
      phone: "+1 555 012 0002",
      line1: "11 Westmoreland Pl",
      city: "St. Louis",
      state: "MO",
      postalCode: "63108",
      country: "United States",
    },
    trackingNumber: "1Z999AA10123456791",
    createdAt: "2026-05-08T10:00:00.000Z",
    updatedAt: "2026-05-09T08:00:00.000Z",
  },
  {
    id: "o-1003",
    number: "LX-10243",
    customer: { id: "c-003", name: "Sofia Chen", email: "sofia@example.com" },
    items: [
      {
        id: "ci-3",
        productId: "p-004",
        productSlug: "soho-leather-tote",
        name: "Soho Leather Tote",
        imageUrl: PRODUCT_IMAGES["p-004"][0],
        price: 289,
        quantity: 1,
        variantId: "p-004-color-black-size-one",
        colorId: "color-black",
        colorName: "Onyx Black",
        sizeId: "size-one",
        sizeLabel: "One Size",
        stock: 24,
      },
      {
        id: "ci-4",
        productId: "p-011",
        productSlug: "selene-pearl-earrings",
        name: "Selene Pearl Earrings",
        imageUrl: PRODUCT_IMAGES["p-011"][0],
        price: 119,
        quantity: 1,
        variantId: "p-011-color-white-size-one",
        colorId: "color-white",
        colorName: "Ivory",
        sizeId: "size-one",
        sizeLabel: "One Size",
        stock: 56,
      },
    ],
    subtotal: 408,
    shipping: 0,
    tax: 32.64,
    discount: 20,
    total: 420.64,
    status: "processing",
    paymentMethod: "paypal",
    shippingMethod: "standard",
    shippingAddress: {
      fullName: "Sofia Chen",
      email: "sofia@example.com",
      phone: "+1 555 012 0003",
      line1: "780 Folsom St",
      city: "San Francisco",
      state: "CA",
      postalCode: "94107",
      country: "United States",
    },
    createdAt: "2026-05-12T10:00:00.000Z",
    updatedAt: "2026-05-12T10:00:00.000Z",
  },
  {
    id: "o-1004",
    number: "LX-10244",
    customer: { id: "c-005", name: "Priya Patel", email: "priya@example.com" },
    items: [
      {
        id: "ci-5",
        productId: "p-007",
        productSlug: "noir-silk-slip-dress",
        name: "Noir Silk Slip Dress",
        imageUrl: PRODUCT_IMAGES["p-007"][0],
        price: 259,
        quantity: 2,
        variantId: "p-007-color-black-size-s",
        colorId: "color-black",
        colorName: "Onyx Black",
        sizeId: "size-s",
        sizeLabel: "S",
        stock: 14,
      },
    ],
    subtotal: 518,
    shipping: 0,
    tax: 41.44,
    discount: 0,
    total: 559.44,
    status: "pending",
    paymentMethod: "card",
    shippingMethod: "express",
    shippingAddress: {
      fullName: "Priya Patel",
      email: "priya@example.com",
      phone: "+1 555 012 0005",
      line1: "55 Marietta St NW",
      city: "Atlanta",
      state: "GA",
      postalCode: "30303",
      country: "United States",
    },
    createdAt: "2026-05-14T10:00:00.000Z",
    updatedAt: "2026-05-14T10:00:00.000Z",
  },
];
